### PR TITLE
Disable Pam's HC integration by default

### PR DESCRIPTION
**Pull request by DotJason**
Removes all Pam's recipe tabs in NEI (quern, churn, etc.) by default, except for garden drops, which are defined elsewhere and are actually used.

### CODE REVIEW

**Comment by wlhlm** [comment]
Thanks! Can you throw in a dependency update?

**Comment by DotJason** [comment]
Sure! Done, I think

**Review by wlhlm — APPROVED** [review]

**Comment by Dream-Master** [comment]
@wlhlm @DotJason the pams machine not craftable but you can get it via quests. Are they now enabled via config if we need them ?

And is it possible to remove other integration as well like GC/GS machines we dont use IC2 or others?

**Comment by wlhlm** [comment]
@Dream-Master Maybe I've missed something, but checking in game, none of the Harvestcraft machines are in the questbook AFAICT. I've checked Quern, Presser, Apiary, Oven, and Churn.

**Pull request merged**
